### ISSUE TITLE
question for paper

### ISSUE THREAD

**Issue by soyekwon** [ningshuliang/PICTURE#11]
Thank you for your work and I think it is a very useful study.
I have a question while reading your thesis.
It seems to be measured for the score of FID and KID when conducting quantitative evaluation on texture transfer. 
In this case, are we measuring the score for the texture image and the result image? 
Without cropping the clothes part of the result image separately?

Thank you.

**Comment by ningshuliang** [comment]
I think we need to crop the clothes part of the generated image, make it the same size with the template texture image, and calculate these two scores.

**Comment by soyekwon** [comment]
> I think we need to crop the clothes part of the generated image, make it the same size with the template texture image, and calculate these two scores.

Thank you for reply.
