### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by Pythonpa** [ningshuliang/PICTURE#2]
Looks very good
When will the code be released?

**Comment by ningshuliang** [comment]
Thank you for your attention. I have uploaded the inference code, feel free to ask if you have any questions.

**Comment by ayd-ocan** [comment]
Thanks for your contribution to community with this repo! I can't reach pre trained weights when i click pre trained weights link. Will you share them?

**Comment by Pythonpa** [comment]
> Thank you for your attention. I have uploaded the inference code, feel free to ask if you have any questions.
OK,I'll  have a try,thank you~
