### ISSUE TITLE
label to colours mapping

### ISSUE THREAD

**Issue by timegate** [ningshuliang/PICTURE#7]
I'm trying to make parsing imgs similar to what you provided,
![image](https://github.com/ningshuliang/PICTURE/assets/16134605/3c3a9393-0efa-463d-b17f-6b5cd48adc5c)
but after the segmentation generation process from VITON-HD, I got imgs similar to below figure.
![image](https://github.com/ningshuliang/PICTURE/assets/16134605/3800138f-8b64-426d-9535-9894bb2ff655)

Could you please provide just a little bit of code snippets, about color and labels?
For example, 
```

labels = { # from https://github.com/shadow2496/VITON-HD
    0:  ['background',  [0]], 
    1:  ['paste',       [2, 4, 7, 8, 9, 10, 11]], 
    2:  ['upper',       [3]],
    3:  ['hair',        [1]],
    4:  ['left_arm',    [5]],
    5:  ['right_arm',   [6]],
    6:  ['noise',       [12]]
}
labels_to_colours = [(0,0,0), ...]

```

**Comment by CiciBEASTARS** [comment]
Hi, I have the same question, how did you solve it?

**Comment by ningshuliang** [comment]
Yes, for SHHQ dataser, I use the official parsing map to train the model, and for VITONHD, you can use the parsing map above. And if you want to train a general model for all dataset, I think you can check https://arxiv.org/abs/1910.09777 this algorithm to get the parsing map for all datasets, and then train a general model.
