### ISSUE TITLE
Error loading model

### ISSUE THREAD

**Issue by RayTang88** [ningshuliang/PICTURE#9]
Thank you for your wonderful work .

I unzipped all the models from Baidu Cloud and got an error when loading Stage1/model_15000.pth. The error is as follows:
![image](https://github.com/user-attachments/assets/09cfd175-a7a3-4ed1-a9a9-13be5dd17bb2)

Here is the md5 value of the downloaded and unzipped model:
![image](https://github.com/user-attachments/assets/9953f867-f730-4a5c-a000-c737e583e9fc)

Thanks again.

**Comment by ningshuliang** [comment]
Sorry for this issue, I will update the checkpoint today~

**Comment by ningshuliang** [comment]
This is the New link~
https://cuhko365-my.sharepoint.com/personal/115010206_link_cuhk_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F115010206%5Flink%5Fcuhk%5Fedu%5Fcn%2FDocuments%2Fpretrain%5Fmodels%2Ezip&parent=%2Fpersonal%2F115010206%5Flink%5Fcuhk%5Fedu%5Fcn%2FDocuments&ga=1

**Comment by RayTang88** [comment]
Thanks for your reply. When I tried to click on the link you sent, I logged into my Microsoft account with my email, and the following problem occurred. It said that I did not have sufficient permissions? Could you please upload it to Baidu Cloud again?
![image](https://github.com/user-attachments/assets/c918e816-d6c2-4c91-a1ef-b724490aae68)
In addition, has the clip of OpenAI been fine-tuned separately? Is it consistent with the one on HuggingFace? If it is consistent, maybe you don’t need to upload it to save your storage space.

**Comment by ningshuliang** [comment]
I have upload to baiduyun again, you can check now. [cid:8256282b-1ea4-4025-a68a-f99f36b8f8f6]
________________________________
发件人: RayTang88 ***@***.***>
发送时间: 2024年8月13日 16:03
收件人: ningshuliang/PICTURE ***@***.***>
抄送: Shuliang Ning (SSE, 115010206) ***@***.***>; Comment ***@***.***>
主题: Re: [ningshuliang/PICTURE] Error loading model (Issue #9)


Thanks for your reply. When I tried to click on the link you sent, I logged into my Microsoft account with my email, and the following problem occurred. It said that I did not have sufficient permissions? Could you please upload it to Baidu Cloud again?
image.png (view on web)<https://github.com/user-attachments/assets/c918e816-d6c2-4c91-a1ef-b724490aae68>
In addition, has the clip of OpenAI been fine-tuned separately? Is it consistent with the one on HuggingFace? If it is consistent, maybe you don’t need to upload it to save your storage space.

―

**Comment by RayTang88** [comment]
Ok，Thank you!

**Comment by ningshuliang** [comment]
why reopen?

**Comment by RayTang88** [comment]
Sorry, I still have some problems after changing the model.
![image](https://github.com/user-attachments/assets/a5ac95aa-2ac5-4ea7-9da7-4b9cda6bb7e3)

I tested the sha265 of the model and it is the same as the value on huggingface.
![image](https://github.com/user-attachments/assets/66887259-4424-48f2-b6be-92a76f693f92)

**Comment by ningshuliang** [comment]
I think you need to change the version of clip model? I know somebody has successed in load my pretrain model. Please check again.

**Comment by RayTang88** [comment]
Ok, I'm checking it！

**Comment by RayTang88** [comment]
Hi，
I modified the code in [Stage1_Text_to_Parsing](https://github.com/ningshuliang/PICTURE/tree/main/Stage1_Text_to_Parsing)
[/test.py] line:167
After modification, it is as follows: model.load_state_dict(torch.load('./pretrain_models/Stage1/model_15000.pth'), strict=False)，
It works fine and gives the same result as you provided.
So I will close this issue now, thank you very much.

**Comment by ningshuliang** [comment]
hh, it seems that you need to check the path .

**Comment by RayTang88** [comment]
I adjusted my last comment. I think it might be because I added “strict=False“ that it worked.Is this the correct modification?
